import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Button,ConfigProvider,Input,InputNumber,Select,Table,Tag,Alert,Modal,Tabs} from 'antd';
import {GameController,browserTransport,drawAppearance,type Painter,type Direction} from '../../../packages/client-runtime/index.js';
import type {Appearance,WorldConfig} from '../../../packages/shared-types/index.js';
import './style.css';
const api=browserTransport(import.meta.env.VITE_API_BASE_URL??'');
function painter(ctx:CanvasRenderingContext2D):Painter{return {rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h);},circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();},text(t,x,y,size,color){ctx.fillStyle=color;ctx.font=`${size}px "Microsoft YaHei",sans-serif`;ctx.textAlign='center';ctx.fillText(t,x,y);}};}
function Preview(){
  const [game]=useState(()=>new GameController(api)),[,setRevision]=useState(0),canvas=useRef<HTMLCanvasElement>(null),avatar=useRef<HTMLCanvasElement>(null),keys=useRef(new Set<string>());
  const [account,setAccount]=useState('traveler-a'),[error,setError]=useState(''),[gender,setGender]=useState<'MALE'|'FEMALE'>('FEMALE'),[base,setBase]=useState(1),[hair,setHair]=useState('INK'),[top,setTop]=useState('SAGE'),[bottom,setBottom]=useState('CREAM'),[dir,setDir]=useState<Direction>('down'),[qty,setQty]=useState(1);
  const run=async(fn:()=>Promise<unknown>)=>{setError('');try{await fn();}catch(e:any){setError(e.message);}};
  useEffect(()=>{game.onChange=()=>setRevision(x=>x+1);const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,textarea,select'))return;keys.current.add(e.key.toLowerCase());if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key.toLowerCase()==='e')void run(()=>game.interact());};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>keys.current.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);let last=performance.now(),frame=0;const loop=(t:number)=>{const k=keys.current;game.tick(Math.min((t-last)/1000,.05),Number(k.has('d')||k.has('arrowright'))-Number(k.has('a')||k.has('arrowleft')),Number(k.has('s')||k.has('arrowdown'))-Number(k.has('w')||k.has('arrowup')));last=t;const c=canvas.current;if(c)game.render(painter(c.getContext('2d')!),c.width,c.height);frame=requestAnimationFrame(loop);};frame=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);game.onChange=()=>{};};},[game]);
  useEffect(()=>{const c=avatar.current;if(!c||!game.boot)return;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);const ap:Appearance={gender,baseAvatarId:`${gender}_${String(base).padStart(2,'0')}`,hairStyleId:`HAIR_${gender}_01`,topStyleId:`TOP_${gender}_01`,bottomStyleId:`BOTTOM_${gender}_01`,shoesId:`SHOES_${gender}_01`,hairColorId:hair,topColorId:top,bottomColorId:bottom,accessoryIds:[]};drawAppearance(painter(ctx),ap,game.boot.colors,130,110,3,dir);},[game.boot,gender,base,hair,top,bottom,dir]);
  const b=game.view?.buildings.find(b=>b.id===game.view?.scene.buildingId),options=Object.entries(game.boot?.colors??{}).map(([value,label])=>({value,label:`${value} ${label}`}));
  return <div className="preview-layout"><main className="game-main"><div className="eyebrow">FUJIA HENGYANG / PLAYABLE PROTOTYPE</div><h1>从白石街开始，<br/>做一笔自己的生意。</h1><p className="intro">横阳镇的一天，从客栈醒来。沿街问价，带上行囊，赚取第一笔铜钱。</p>
    {!game.boot?<div className="login-card"><Tag color="green">本地开发入口</Tag><h2>初到横阳</h2><p>输入测试账号，开始或继续当前服务中的旅程。</p><Input aria-label="测试账号" value={account} onChange={e=>setAccount(e.target.value)}/><Button type="primary" size="large" onClick={()=>run(()=>game.loginDev(account))}>进入小镇 →</Button><small>正式小游戏使用微信登录。演示服务重启会清空存档。</small></div>:!game.player?.appearance?<div className="creation"><div><Tag color="green">第一步 · 创建角色</Tag><h2>这是你的横阳故事</h2><Select aria-label="角色性别" value={gender} onChange={setGender} options={[{value:'MALE',label:'男'},{value:'FEMALE',label:'女'}]}/><div className="six">{Array.from({length:6},(_,i)=><Button type={base===i+1?'primary':'default'} key={i} onClick={()=>setBase(i+1)}>形象 {i+1}</Button>)}</div>{[['发色',hair,setHair],['上衣',top,setTop],['下装',bottom,setBottom]].map(([label,value,set]:any)=><label className="color-row" key={label}>{label}<Select value={value} onChange={set} options={options}/></label>)}<Button type="primary" size="large" disabled={game.busy} onClick={()=>run(()=>game.create(gender,`${gender}_${String(base).padStart(2,'0')}`,hair,top,bottom))}>确认形象，入住客栈</Button></div><div className="avatar-preview"><canvas ref={avatar} width="260" height="220"/><div>{(['up','left','down','right'] as Direction[]).map((d,i)=><Button key={d} onClick={()=>setDir(d)}>{['背面','左侧','正面','右侧'][i]}</Button>)}</div><small>原型组合素材 · 确认前可自由调整</small></div></div>:<><div className="scene-bar"><span>◈ {game.view?.scene.name}</span><span>{game.view?.phase} · 北京时间</span></div><div className="canvas-wrap"><canvas aria-label="横阳游戏场景" ref={canvas} width="960" height="560"/><div className="controls"><div className="dpad">{[['↑','w'],['←','a'],['↓','s'],['→','d']].map(([symbol,key])=><button key={key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);keys.current.add(key);}} onPointerUp={()=>keys.current.delete(key)} onPointerCancel={()=>keys.current.delete(key)}>{symbol}</button>)}</div><Button type="primary" disabled={game.busy||!!game.pending} onClick={()=>run(()=>game.interact())}>{game.nearby()?.label??'靠近门口或人物'} [E]</Button></div></div><div className="message">{game.message}</div></>}
    {(error||game.offline)&&<Alert type="warning" showIcon message={error||game.message} action={game.pending||game.offline?<Button onClick={()=>run(()=>game.retry())}>{game.pending?'重试待确认操作':'重新连接'}</Button>:null}/>}</main>
    <aside><div className="side-card"><span className="eyebrow">你的旅程</span><h2>{game.player?.nickname??'旅人，欢迎'}</h2><div className="cash">{game.player?.cash??'—'} <span>文铜钱</span></div><div className="stat"><span>体力</span><b>{game.player?.stamina??100} / 100</b></div><p>WASD / 方向键移动<br/>E 或按钮与附近人物、建筑互动</p>{game.boot&&<Button block onClick={()=>{keys.current.clear();game.logout();}}>退出并验证存档</Button>}</div><div className="side-card"><h3>第一桶金</h3><ol><li>创建自己的角色</li><li>走到客栈下方出口</li><li>进入东侧街坊杂货铺</li><li>买入鸣山大米</li><li>继续向东，到白石商行卖出</li></ol></div><div className="side-card"><h3>旧行囊</h3>{Object.entries(game.player?.inventory??{}).map(([id,count])=><div className="stat" key={id}><span>{id==='RICE_01'?'鸣山大米':'横阳米糕'}</span><b>× {count}</b></div>)}{!Object.keys(game.player?.inventory??{}).length&&<p>行囊还空着，去街上逛逛。</p>}</div>
    {b&&Object.keys(b.stock).length>0&&<div className="side-card"><h3>{b.name}</h3><InputNumber aria-label="交易数量" min={1} max={99} value={qty} onChange={v=>setQty(v??1)}/>{Object.entries(b.stock).map(([id,s])=><div className="goods" key={id}><strong>{id==='RICE_01'?'鸣山大米':'横阳米糕'}</strong><small>今日每方向限量 {s.dailyLimit} 件</small><Button disabled={game.busy||!!game.pending} onClick={()=>run(()=>game.trade('buy',id,qty))}>买入 · {s.buy} 文</Button><Button disabled={game.busy||!!game.pending} onClick={()=>run(()=>game.trade('sell',id,qty))}>卖出 · {s.sell} 文</Button></div>)}</div>}
    {b&&['SALON','CLOTH'].includes(b.buildingType)&&<div className="side-card"><h3>{b.name}</h3>{game.boot?.appearances.filter(a=>a.genderScope===game.player?.appearance?.gender&&(b.buildingType==='SALON'?a.partType==='HAIR':['TOP','BOTTOM','SHOES'].includes(a.partType))).map(a=><div className="goods" key={a.id}><b>{a.name} · {a.price} 文</b>{b.buildingType==='CLOTH'&&!game.player?.cosmetics.includes(a.id)?<Button disabled={game.busy} onClick={()=>run(()=>game.write('/v1/appearance/purchase',{buildingId:b.id,appearanceId:a.id}))}>购买</Button>:<Button disabled={game.busy} onClick={()=>run(()=>game.write('/v1/appearance/change',{buildingId:b.id,appearanceId:a.id,colorId:'SAGE'}))}>{b.buildingType==='SALON'?'付费理发':'穿上'}</Button>}</div>)}</div>}
    <details className="side-card"><summary>交易记录</summary>{game.player?.ledger.slice().reverse().map(l=><div className="ledger" key={l.id}><span>{l.type}</span><b>{l.amount>0?'+':''}{l.amount} 文</b></div>)}</details></aside></div>;
}
function Admin(){const [token,setToken]=useState(''),[world,setWorld]=useState<WorldConfig|null>(null),[json,setJson]=useState(''),[releases,setReleases]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const load=async()=>{const w=await api('/admin/world',undefined,token);setWorld(w);setJson(JSON.stringify(w,null,2));setReleases((await api('/admin/releases',undefined,token)).releases);};
 return <div className="admin"><div className="eyebrow">WORLD OPERATIONS / CONFIGURATION</div><h1>横阳世界管理</h1><p>草稿经过校验再发布。名称可调整，内部 ID 保持不变。回滚时，将历史版本复制为新草稿后重新发布。</p><div className="admin-login"><Input.Password aria-label="后台访问凭据" placeholder="后台访问凭据（仅保存在当前页面内存）" value={token} onChange={e=>setToken(e.target.value)}/><Button loading={busy} type="primary" onClick={()=>run(load)}>连接后台</Button></div>{error&&<Alert type="error" message={error} showIcon/>}{world&&<><div className="admin-stats"><div>当前发布 <b>v{world.configVersion}</b></div><div>场景 <b>{world.scenes.length}</b></div><div>地块 <b>{world.plots.length}</b></div><div>建筑 <b>{world.buildings.length}</b></div></div><Tabs items={[{key:'buildings',label:'建筑与营业',children:<Table rowKey="id" dataSource={world.buildings} pagination={false} columns={[{title:'稳定 ID',dataIndex:'id'},{title:'名称',dataIndex:'name'},{title:'类型',dataIndex:'buildingType'},{title:'营业时间',render:(_,r)=>r.openingHours.join(' — ')},{title:'状态',render:(_,r)=><Tag color={r.enabled?'green':'default'}>{r.enabled?'启用':'停用'}</Tag>}]}/>},{key:'npcs',label:'人物',children:<Table rowKey="id" dataSource={world.npcs} columns={[{title:'ID',dataIndex:'id'},{title:'名称',dataIndex:'name'},{title:'场景',dataIndex:'sceneId'},{title:'名称锁定',render:(_,r)=>r.nameLocked?'是':'否'}]}/>},{key:'appearance',label:'外观',children:<Table rowKey="id" dataSource={world.appearances} columns={[{title:'ID',dataIndex:'id'},{title:'名称',dataIndex:'name'},{title:'类型',dataIndex:'partType'},{title:'价格',dataIndex:'price'},{title:'配色',render:(_,r)=>r.colors.join(', ')}]}/>},{key:'edit',label:'配置草稿',children:<><Alert type="info" message="编辑完整 JSON 后保存为独立草稿。基础道路拓扑、核心人物名称及已有 ID 由服务端保护。"/><Input.TextArea aria-label="世界配置 JSON" className="json-editor" value={json} onChange={e=>setJson(e.target.value)} rows={22}/><Button loading={busy} type="primary" onClick={()=>run(async()=>{await api('/admin/releases',{config:JSON.parse(json),basedOn:world.configVersion},token);await load();})}>保存草稿</Button></>} ]}/><h2>版本发布</h2><Table rowKey="id" dataSource={releases} columns={[{title:'版本',dataIndex:'version'},{title:'状态',render:(_,r)=><Tag>{r.status}</Tag>},{title:'操作',render:(_,r)=><>{['DRAFT','TEST'].includes(r.status)&&<Button loading={busy} onClick={()=>Modal.confirm({title:r.status==='DRAFT'?'校验此草稿？':'发布此版本？',content:r.status==='DRAFT'?'校验配置引用、稳定 ID 和规则。TEST 不会影响在线玩家。':'新加载的场景将使用此版本。',onOk:()=>run(async()=>{await api(`/admin/releases/${r.id}/transition`,{status:r.status==='DRAFT'?'TEST':'PUBLISHED'},token);await load();})})}>{r.status==='DRAFT'?'校验为 TEST':'发布'}</Button>}<Button onClick={()=>setJson(JSON.stringify(r.config,null,2))}>复制配置到编辑器</Button></>} ]}/></>}</div>;
}
function App(){const [tab,setTab]=useState('play');return <ConfigProvider theme={{token:{colorPrimary:'#527c69',borderRadius:8,fontFamily:'"Microsoft YaHei",sans-serif'}}}><header><a className="brand" onClick={()=>setTab('play')}><span>富</span>富甲横阳 <small>开发工作台</small></a><nav><button className={tab==='play'?'active':''} onClick={()=>setTab('play')}>试玩原型</button><button className={tab==='admin'?'active':''} onClick={()=>setTab('admin')}>世界管理</button><Tag>V2.2 · 里程碑 01</Tag></nav></header>{tab==='play'?<Preview/>:<Admin/>}<footer>富甲横阳 · 原型开发版　/　正式美术、第二及第三阶段玩法尚未交付</footer></ConfigProvider>}
createRoot(document.getElementById('root')!).render(<App/>);
