ALTER TABLE "players" ADD COLUMN "storyFlags" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "players" ALTER COLUMN "sceneId" SET DEFAULT 'INTERIOR_B_INN_GUEST_ROOM';
ALTER TABLE "players" ALTER COLUMN "x" SET DEFAULT 6;
ALTER TABLE "players" ALTER COLUMN "y" SET DEFAULT 7;
