import test from 'node:test';
import assert from 'node:assert/strict';
import {drawBuildingAsset,drawSpriteSheet,drawSpriteSheetOrFallback,emptyPortraitState,portraitState,spriteFrame,ImageAssetStore,type ImageSource} from '../packages/client-runtime/assets.js';

const image:ImageSource={width:1254,height:1254};
test('建筑资源使用 origin 绘制并保留前景元数据',()=>{const calls:any[]=[];const target={drawImage:(...args:any[])=>calls.push(args)};drawBuildingAsset(target,image,{assetKey:'test',imagePath:'/test.png',worldX:32.5,worldY:20,renderWidth:320,renderHeight:384,originX:.5,originY:1,depth:30,foreground:{assetKey:'fg',imagePath:'/fg.png',offsetX:0,offsetY:-128,depth:50}});assert.deepEqual(calls[0].slice(5),[-127.5,-364,320,384]);});
test('spritesheet 按方向行、帧列和 foot anchor 切帧',()=>{const calls:any[]=[];const target={drawImage:(...args:any[])=>calls.push(args)};const asset={assetKey:'npc',imagePath:'/npc.png',frameWidth:313,frameHeight:313,columns:4,rows:4,directionRows:{down:0,left:1,right:2,up:3},framesPerDirection:4,footAnchorX:156,footAnchorY:300,renderScale:1};assert.deepEqual(spriteFrame(asset,'right',2),{sx:626,sy:626,sw:313,sh:313});drawSpriteSheet(target,image,asset,'right',2,100,200);assert.deepEqual(calls[0].slice(1,5),[626,626,313,313]);assert.deepEqual(calls[0].slice(5),[-56,-100,313,313]);});
test('portrait 默认降级且重要模式提供双槽和压暗',()=>{assert.deepEqual(emptyPortraitState(),{portraitMode:false,backgroundDim:false});const left={assetKey:'left',imagePath:'/left.png',preferredWidth:256,preferredHeight:360,slot:'left' as const,originX:.5,originY:1};assert.deepEqual(portraitState(left,undefined,'left'),{portraitMode:true,backgroundDim:true,left,right:undefined,speaking:'left'});});

test('正式图片缺失时调用 fallback，资源加载结果可缓存',async()=>{const asset={assetKey:'npc',imagePath:'/npc.png',frameWidth:64,frameHeight:64,columns:4,rows:4,directionRows:{down:0,left:1,right:2,up:3},framesPerDirection:4,footAnchorX:32,footAnchorY:60,renderScale:1};let fallback=0;drawSpriteSheetOrFallback({drawImage:()=>{}},undefined,asset,'down',0,0,0,()=>fallback++);assert.equal(fallback,1);const store=new ImageAssetStore(),loaded={width:64,height:64};assert.equal(await store.load('test',async()=>loaded),loaded);assert.equal(store.get('test'),loaded);});
