import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {MemoryRepository} from '../apps/server/src/repository.js';
import {buildApp} from '../apps/server/src/app.js';
import {GameService} from '../apps/server/src/service.js';
import {validateWorld} from '../apps/server/src/config.js';
import {initialWorld} from '../packages/game-config/index.js';
import {isOpen,phaseAt} from '../packages/game-rules/index.js';
const env={mode:'development',appEnv:'DEV',port:8080,jwtSecret:'test-jwt-secret-thirty-two-characters-long',subjectSecret:'test-subject-secret-thirty-two-characters',adminToken:'test-admin-token-thirty-two-characters-long',allowDevAuth:true,appId:'',appSecret:'',adminOrigin:'http://localhost:5173',assetBase:'http://localhost:8080/assets'};
const appearance=(gender='FEMALE')=>({requestId:randomUUID(),gender,baseAvatarId:`${gender}_04`,hairColorId:'INK',topColorId:'SAGE',bottomColorId:'CREAM'});
async function fixture(){const repo=new MemoryRepository(),p=await repo.login(randomUUID()),service=new GameService(repo,()=>new Date('2026-09-05T02:00:00Z'));await service.action(p.id,'create',appearance());return {repo,p,service};}
test('北京时间边界和跨午夜营业窗口',()=>{assert.equal(phaseAt(new Date('2026-09-05T11:59:59Z')),'傍晚');assert.equal(phaseAt(new Date('2026-09-05T12:00:00Z')),'夜晚');assert.equal(phaseAt(new Date('2026-09-05T16:00:00Z')),'深夜');assert.equal(isOpen(['20:00','02:00'],new Date('2026-09-05T17:00:00Z')),true);assert.equal(isOpen(['20:00','02:00'],new Date('2026-09-05T18:00:00Z')),false);});
test('男女各六个基础角色，初次创建重试不重复发钱',async()=>{for(const gender of ['MALE','FEMALE'])assert.equal(initialWorld.appearances.filter(a=>a.partType==='BASE'&&a.genderScope===gender).length,6);const repo=new MemoryRepository(),p=await repo.login('a'),s=new GameService(repo),body=appearance();await Promise.all([s.action(p.id,'create',body),s.action(p.id,'create',body)]);const saved=await repo.player(p.id);assert.equal(saved.cash,120);assert.equal(saved.ledger.length,1);await assert.rejects(()=>s.action(p.id,'create',appearance()));assert.equal((await repo.login('a')).appearance?.baseAvatarId,'FEMALE_04');});
test('完整 HTTP 首登、建角、出门、买入卖出以及账本链路',async()=>{
 const repo=new MemoryRepository(),app=await buildApp(repo,env);try{
 const login=(await app.inject({method:'POST',url:'/v1/auth/dev',payload:{account:'flow'}})).json(),headers={authorization:`Bearer ${login.token}`};
 const post=async(url:string,payload:object)=>{const r=await app.inject({method:'POST',url,headers,payload:{requestId:randomUUID(),...payload}});assert.equal(r.statusCode,200,r.body);return r.json();};
 assert.equal((await app.inject({url:'/v1/world/scenes/STREET_BAISHI_01',headers})).statusCode,409);
 await post('/v1/player/appearance/create',appearance());await post('/v1/world/portal',{portalId:'EXIT_B_INN'});
 const scene=(await app.inject({url:'/v1/world/scenes/STREET_BAISHI_01',headers})).json();assert.equal(scene.plots.length,10);assert.equal(scene.buildings.length,5);assert.equal(scene.npcs.length,3);
 for(const x of [15,21,23])await post('/v1/player/move',{x,y:37});
 await post('/v1/world/enter',{plotId:'P_BAISHI_002'});
 const buy={requestId:randomUUID(),buildingId:'B_GROCERY',itemId:'RICE_01',quantity:1};const first=await post('/v1/economy/buy',buy);const retry=await post('/v1/economy/buy',buy);assert.deepEqual(first,retry);assert.equal(first.player.cash,108);
 await post('/v1/world/portal',{portalId:'EXIT_B_GROCERY'});for(const x of [29,35,37])await post('/v1/player/move',{x,y:37});await post('/v1/world/enter',{plotId:'P_BAISHI_003'});const sold=await post('/v1/economy/sell',{buildingId:'B_TRADE',itemId:'RICE_01',quantity:1});assert.equal(sold.player.cash,124);assert.equal(sold.player.inventory.RICE_01,undefined);assert.deepEqual(sold.player.ledger.map((l:any)=>l.after),[120,108,124]);
 }finally{await app.close();}
});
test('伪造价格、数量、身份和未建角交易被拒绝',async()=>{const app=await buildApp(new MemoryRepository(),env);try{assert.equal((await app.inject({url:'/v1/bootstrap'})).statusCode,401);const auth=(await app.inject({method:'POST',url:'/v1/auth/dev',payload:{account:'bad'}})).json(),headers={authorization:`Bearer ${auth.token}`};for(const quantity of [-1,0,1.5,100000000])assert.equal((await app.inject({method:'POST',url:'/v1/economy/buy',headers,payload:{requestId:randomUUID(),buildingId:'B_GROCERY',itemId:'RICE_01',quantity}})).statusCode,400);assert.equal((await app.inject({method:'POST',url:'/v1/economy/buy',headers,payload:{requestId:randomUUID(),buildingId:'B_GROCERY',itemId:'RICE_01',quantity:1,price:0}})).statusCode,400);}finally{await app.close();}});
test('交易失败回滚，库存不足、非店铺、负余额拒绝',async()=>{const {repo,p,service:s}=await fixture();await assert.rejects(()=>s.action(p.id,'buy',{requestId:randomUUID(),buildingId:'B_GROCERY',itemId:'RICE_01',quantity:1}));repo.players.get(p.id)!.sceneId='INTERIOR_B_GROCERY';await assert.rejects(()=>s.action(p.id,'sell',{requestId:randomUUID(),buildingId:'B_GROCERY',itemId:'RICE_01',quantity:1}));await assert.rejects(()=>s.action(p.id,'buy',{requestId:randomUUID(),buildingId:'B_GROCERY',itemId:'RICE_01',quantity:20}));assert.equal((await repo.player(p.id)).cash,120);assert.equal((await repo.player(p.id)).ledger.length,1);});
test('同一请求号不同载荷冲突，并发重试只扣一次',async()=>{const {repo,p,service:s}=await fixture();repo.players.get(p.id)!.sceneId='INTERIOR_B_GROCERY';const body={requestId:randomUUID(),buildingId:'B_GROCERY',itemId:'RICE_01',quantity:1};await Promise.all(Array.from({length:20},()=>s.action(p.id,'buy',body)));assert.equal((await repo.player(p.id)).cash,108);await assert.rejects(()=>s.action(p.id,'buy',{...body,quantity:2}),/请求编号/);});
test('外观所有权、性别兼容、Ghost同步',async()=>{const {repo,p,service:s}=await fixture();repo.players.get(p.id)!.sceneId='INTERIOR_B_CLOTH';const change={requestId:randomUUID(),buildingId:'B_CLOTH',appearanceId:'TOP_FEMALE_02',colorId:'ROSE'};await assert.rejects(()=>s.action(p.id,'changeAppearance',change),/尚未拥有/);await s.action(p.id,'purchaseAppearance',{requestId:randomUUID(),buildingId:'B_CLOTH',appearanceId:'TOP_FEMALE_02'});await s.action(p.id,'changeAppearance',change);const saved=await repo.player(p.id);assert.equal(saved.cash,90);assert.equal(saved.appearance?.baseAvatarId,'FEMALE_04');assert.equal((await repo.ghosts('other'))[0].appearance.topStyleId,'TOP_FEMALE_02');assert.equal((await repo.ghosts('other'))[0].appearance.topColorId,'ROSE');await assert.rejects(()=>s.action(p.id,'purchaseAppearance',{requestId:randomUUID(),buildingId:'B_CLOTH',appearanceId:'TOP_MALE_02'}));});
test('场景碰撞和远程入口被拒绝',async()=>{const {p,service:s}=await fixture();await assert.rejects(()=>s.action(p.id,'move',{requestId:randomUUID(),x:12,y:1}),/移动过远/);await assert.rejects(()=>s.action(p.id,'enter',{requestId:randomUUID(),plotId:'P_BAISHI_002'}));});
test('配置引用、道路、锁定名、版本发布与回滚',async()=>{const repo=new MemoryRepository();validateWorld(initialWorld);const bad=structuredClone(initialWorld);bad.npcs[0].name='改名';assert.throws(()=>validateWorld(bad,initialWorld),/锁定/);const road=structuredClone(initialWorld);road.roads[0].connects=[];assert.throws(()=>validateWorld(road,initialWorld),/道路/);const changed=structuredClone(initialWorld);changed.buildings[1].name='新杂货铺';const r=await repo.draft(validateWorld(changed,initialWorld),1);await assert.rejects(()=>repo.transition(r.id,'PUBLISHED'));await repo.transition(r.id,'TEST');await repo.transition(r.id,'PUBLISHED');assert.equal((await repo.world()).buildings[1].name,'新杂货铺');const rollback=await repo.draft(initialWorld,2);await repo.transition(rollback.id,'TEST');await repo.transition(rollback.id,'PUBLISHED');assert.equal((await repo.world()).configVersion,3);assert.equal((await repo.world()).buildings[1].name,'街坊杂货铺');});
test('生产环境禁止开发登录、后台鉴权',async()=>{const app=await buildApp(new MemoryRepository(),{...env,mode:'production',appEnv:'PROD',allowDevAuth:false});try{assert.equal((await app.inject({method:'POST',url:'/v1/auth/dev',payload:{account:'x'}})).statusCode,404);assert.equal((await app.inject({url:'/admin/world'})).statusCode,401);}finally{await app.close();}});
