import Phaser from 'phaser';
import { GameController, drawAppearance, formatQuestTracker, ImageAssetStore, type Direction, type Painter } from '../../../packages/client-runtime/index.js';
import type { Appearance } from '../../../packages/shared-types/index.js';
import { createWebPlatform } from './web-platform';
import './style.css';
import './quest.css';
import './shop.css';

const WIDTH=960,HEIGHT=540,TILE=32;
const platform=createWebPlatform(import.meta.env.VITE_API_BASE_URL??'');
const controller=new GameController(platform.transport);
const imageAssets=new ImageAssetStore();
const pressed=new Set<string>();
type Draft={gender:'MALE'|'FEMALE';base:number;skin:string;hair:string;top:string;bottom:string;direction:Direction};
const draft:Draft={gender:'FEMALE',base:1,skin:'SKIN_LIGHT',hair:'INK',top:'SAGE',bottom:'CREAM',direction:'down'};
const byId=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const auth=byId<HTMLElement>('auth'),create=byId<HTMLElement>('create'),hud=byId<HTMLElement>('hud'),status=byId<HTMLElement>('status'),message=byId<HTMLElement>('message'),createMessage=byId<HTMLElement>('create-message'),questPanel=byId<HTMLElement>('quest-panel'),quest=byId<HTMLElement>('quest'),questToggle=byId<HTMLButtonElement>('quest-toggle'),questToggleIcon=byId<HTMLElement>('quest-toggle-icon'),shopPanel=byId<HTMLElement>('shop-panel'),shopTitle=byId<HTMLElement>('shop-title'),shopBalance=byId<HTMLElement>('shop-balance'),shopItems=byId<HTMLElement>('shop-items'),shopFeedback=byId<HTMLElement>('shop-feedback'),inventory=byId<HTMLElement>('inventory');
let questCollapsed=false;
const groundKey='baishi-ground';
function color(value:string){const hex=value.replace('#',''),rgb=hex.slice(0,6).padEnd(6,'0');return {value:parseInt(rgb,16),alpha:hex.length===8?parseInt(hex.slice(6),16)/255:1};}
function option(select:HTMLSelectElement,value:string,label:string){const item=document.createElement('option');item.value=value;item.textContent=label;select.append(item);}
function draftAppearance():Appearance{return {gender:draft.gender,baseAvatarId:`${draft.gender}_${String(draft.base).padStart(2,'0')}`,skinColorId:draft.skin,hairStyleId:`HAIR_${draft.gender}_01`,topStyleId:`TOP_${draft.gender}_01`,bottomStyleId:`BOTTOM_${draft.gender}_01`,shoesId:`SHOES_${draft.gender}_01`,hairColorId:draft.hair,topColorId:draft.top,bottomColorId:draft.bottom,accessoryIds:[]};}
function renderPreview(){const boot=controller.boot;if(!boot)return;const canvas=byId<HTMLCanvasElement>('appearance-preview'),ctx=canvas.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#edf3e8';ctx.fillRect(0,0,canvas.width,canvas.height);const painter:Painter={rect:(x,y,w,h,fill)=>{const c=color(fill);ctx.globalAlpha=c.alpha;ctx.fillStyle=`#${c.value.toString(16).padStart(6,'0')}`;ctx.fillRect(x,y,w,h);ctx.globalAlpha=1;},circle:(x,y,r,fill)=>{const c=color(fill);ctx.globalAlpha=c.alpha;ctx.fillStyle=`#${c.value.toString(16).padStart(6,'0')}`;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;},text:(text,x,y,size,fill)=>{ctx.fillStyle=fill;ctx.font=`${size}px Microsoft YaHei`;ctx.textAlign='center';ctx.fillText(text,x,y);}};drawAppearance(painter,draftAppearance(),boot.colors,canvas.width/2,canvas.height/2,3,draft.direction,0);}function refreshCreation(){const boot=controller.boot;if(!boot)return;const colors=Object.entries(boot.colors),skin=colors.filter(([id])=>id.startsWith('SKIN_')),wear=colors.filter(([id])=>!id.startsWith('SKIN_'));for(const [id,list,value] of [['skin',skin,draft.skin],['hair',wear,draft.hair],['top',wear,draft.top],['bottom',wear,draft.bottom]] as const){const select=byId<HTMLSelectElement>(id);select.replaceChildren();for(const [key,hex] of list)option(select,key,`${key.replace('SKIN_','')} ${hex}`);select.value=value;}const bases=byId<HTMLElement>('base-buttons');bases.replaceChildren();for(let i=1;i<=6;i++){const button=document.createElement('button');button.textContent=`形象 ${i}`;button.classList.toggle('active',draft.base===i);button.onclick=()=>{draft.base=i;refreshCreation();};bases.append(button);}for(const button of document.querySelectorAll<HTMLButtonElement>('[data-gender]'))button.classList.toggle('active',button.dataset.gender===draft.gender);for(const button of document.querySelectorAll<HTMLButtonElement>('[data-direction]'))button.classList.toggle('active',button.dataset.direction===draft.direction);renderPreview();}
function refreshShopPanel(){const shop=controller.shopPanel(),nearClerk=controller.view?.npcs.some(n=>Math.hypot(n.x-controller.x,n.y-controller.y)<6),visible=!!shop&&!!nearClerk;shopPanel.classList.toggle('hidden',!visible);if(!shop||!visible)return;shopTitle.textContent=shop.title;shopBalance.textContent=`铜钱 ${shop.balance} 文`;shopItems.replaceChildren();for(const item of shop.items){const row=document.createElement('article'),icon=document.createElement('span'),detail=document.createElement('div'),name=document.createElement('strong'),owned=document.createElement('small'),prices=document.createElement('small'),actions=document.createElement('div'),buy=document.createElement('button'),sell=document.createElement('button');row.className='shop-item';icon.className='shop-icon';icon.textContent=item.icon;name.textContent=item.name;owned.textContent=`持有 ×${item.owned}`;prices.textContent=`买入 ${item.buyPrice} 文　卖出 ${item.sellPrice} 文`;buy.textContent=`买入 · ${item.buyPrice} 文`;sell.textContent=`出售 · ${item.sellPrice} 文`;buy.disabled=controller.busy||!!controller.pending;sell.disabled=controller.busy||!!controller.pending;buy.onclick=()=>void run(()=>controller.trade('buy',item.id));sell.onclick=()=>void run(()=>controller.trade('sell',item.id));detail.append(name,owned,prices);actions.append(buy,sell);row.append(icon,detail,actions);shopItems.append(row);}shopFeedback.textContent=controller.message;}
function refreshQuestPanel(){const task=controller.questTracker()[0];quest.textContent=task?formatQuestTracker(task):'暂无进行中的任务';questPanel.classList.toggle('completed',!!task?.completed);quest.classList.toggle('hidden',questCollapsed);questToggle.setAttribute('aria-expanded',String(!questCollapsed));questToggleIcon.textContent=questCollapsed?'▼':'▲';}function syncUi(){const player=controller.player;auth.classList.toggle('hidden',!!controller.boot);create.classList.toggle('hidden',!controller.boot||!!player?.appearance);hud.classList.toggle('hidden',!player?.appearance);if(controller.boot&&!player?.appearance)refreshCreation();status.textContent=player?.appearance?`${controller.view?.scene.name??'横阳'} · ${controller.view?.phase??''} · ${player.cash} 文`:'';message.textContent=controller.message;createMessage.textContent=controller.boot&&!player?.appearance?controller.message:'';if(player?.appearance){refreshQuestPanel();refreshShopPanel();const bag=Object.entries(player.inventory).map(([id,n])=>`${id==='RICE_01'?'鸣山大米':id} ×${n}`).join('　');inventory.textContent=bag?`行囊：${bag}`:'行囊：空';}byId<HTMLButtonElement>('interact').textContent=controller.nearby()?.label??'互动';}
async function run(action:()=>Promise<unknown>){try{await action();}catch(error:any){controller.message=error.message??'操作失败';}syncUi();}

class BaishiScene extends Phaser.Scene {private graphics!:Phaser.GameObjects.Graphics;private ground!:Phaser.GameObjects.Image;private labels:Phaser.GameObjects.Text[]=[];private labelIndex=0;constructor(){super('baishi');}preload(){this.load.image(groundKey,'/scene-layers/baishi/ground/baishi_composition_approved_v01.png');}create(){this.ground=this.add.image(0,0,groundKey).setOrigin(0).setDisplaySize(48*TILE,48*TILE).setDepth(0).setVisible(false);this.graphics=this.add.graphics().setDepth(10);this.input.keyboard?.on('keydown-E',()=>void run(()=>controller.interact()));this.input.keyboard?.on('keydown-SPACE',()=>void run(()=>controller.interact()));platform.onLifecycle(state=>{if(state==='hide')pressed.clear();});controller.onChange=syncUi;syncUi();}update(_time:number,delta:number){const keyboard=this.input.keyboard;const dx=Number(pressed.has('right')||keyboard?.addKey('RIGHT').isDown||keyboard?.addKey('D').isDown)-Number(pressed.has('left')||keyboard?.addKey('LEFT').isDown||keyboard?.addKey('A').isDown);const dy=Number(pressed.has('down')||keyboard?.addKey('DOWN').isDown||keyboard?.addKey('S').isDown)-Number(pressed.has('up')||keyboard?.addKey('UP').isDown||keyboard?.addKey('W').isDown);controller.tick(Math.min(delta/1000,.05),dx,dy);this.render();}private render(){const view=controller.view;this.graphics.clear();this.labelIndex=0;const painter:Painter={rect:(x,y,w,h,fill)=>{const c=color(fill);this.graphics.fillStyle(c.value,c.alpha);this.graphics.fillRect(x,y,w,h);},circle:(x,y,r,fill)=>{const c=color(fill);this.graphics.fillStyle(c.value,c.alpha);this.graphics.fillCircle(x,y,r);},text:(text,x,y,size,fill)=>{let label=this.labels[this.labelIndex++];if(!label){label=this.add.text(0,0,'',{fontFamily:'Microsoft YaHei',fontSize:size,color:'#ffffff',stroke:'#23352b',strokeThickness:2}).setOrigin(.5).setDepth(20);this.labels.push(label);}label.setText(text).setPosition(x,y).setFontSize(size).setColor(fill).setVisible(true);}};if(controller.boot&&!controller.player?.appearance){this.ground.setVisible(false);drawAppearance(painter,draftAppearance(),controller.boot.colors,WIDTH/2,HEIGHT/2,4,draft.direction,controller.walkTime);}else if(view){const ox=WIDTH/2-controller.x*TILE,oy=HEIGHT/2-controller.y*TILE;this.ground.setVisible(view.scene.id==='STREET_BAISHI_01').setPosition(ox,oy);controller.render(painter,WIDTH,HEIGHT,false,false,true);}else this.ground.setVisible(false);for(let i=this.labelIndex;i<this.labels.length;i++)this.labels[i].setVisible(false);}}
new Phaser.Game({type:Phaser.CANVAS,width:WIDTH,height:HEIGHT,parent:'game',backgroundColor:'#b7cba5',scene:[BaishiScene],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});
byId<HTMLInputElement>('account').value=platform.readLocal('fjhy.devAccount')??'web-traveler';byId<HTMLButtonElement>('login').onclick=()=>void run(async()=>{const account=byId<HTMLInputElement>('account').value.trim()||'web-traveler';platform.writeLocal('fjhy.devAccount',account);await controller.loginDev(account);});
for(const id of ['skin','hair','top','bottom'] as const)byId<HTMLSelectElement>(id).onchange=e=>{draft[id]=String((e.target as HTMLSelectElement).value);renderPreview();};for(const button of document.querySelectorAll<HTMLButtonElement>('[data-gender]'))button.onclick=()=>{draft.gender=button.dataset.gender as Draft['gender'];refreshCreation();};for(const button of document.querySelectorAll<HTMLButtonElement>('[data-direction]'))button.onclick=()=>{draft.direction=button.dataset.direction as Direction;refreshCreation();};byId<HTMLButtonElement>('create-player').onclick=()=>void run(()=>controller.create(draft.gender,`${draft.gender}_${String(draft.base).padStart(2,'0')}`,draft.skin,draft.hair,draft.top,draft.bottom));
byId<HTMLButtonElement>('interact').onclick=()=>void run(()=>controller.interact());for(const button of document.querySelectorAll<HTMLButtonElement>('#dpad button')){const direction=button.dataset.move!;const set=(on:boolean)=>on?pressed.add(direction):pressed.delete(direction);button.onpointerdown=e=>{e.preventDefault();button.setPointerCapture(e.pointerId);set(true);};button.onpointerup=()=>set(false);button.onpointercancel=()=>set(false);button.onpointerleave=()=>set(false);button.oncontextmenu=e=>e.preventDefault();}window.addEventListener('blur',()=>pressed.clear());
questToggle.onclick=()=>{questCollapsed=!questCollapsed;refreshQuestPanel();};
